export enum Message {
  NOT_FOUND = 'NOT_FOUND',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  INVALID_EMAIL_PASSWORD = 'INVALID_EMAIL_PASSWORD',
  INVALID_ID = 'INVALID_ID',
  MODALITY_DISABLE = 'MODALITY_DISABLE',
  TEACHER_DISABLE = 'TEACHER_DISABLE',
  INCOMPATIBLE_MODALITY = 'INCOMPATIBLE_MODALITY',
  AGE_CONSTRAINT = 'AGE_CONSTRAINT',
}
