export enum ModuleName {
  ADMIN = 'ADMIN',
  ATHLETES = 'ATHLETES',
  CLASSES = 'CLASSES',
  MODALITIES = 'MODALITIES',
  PAYMENT = 'PAYMENT',
  PLANS = 'PLANS',
  TEACHERS = 'TEACHERS',
  VISITS = 'VISITS',
  COMMON = 'COMMON',
}
